FROM node:16 as build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .


ARG BASE_URL
ARG VITE_BASE_URL
ARG VITE_NETWORK
ARG VITE_CONTRACT_DAO
ARG VITE_CONTRACT_USDT
ARG VITE_ROUTER_WALLET
ARG VITE_ROUTER_EXPLORER_NEAR_HASH
ARG VITE_URL_APIP_PRICE
ARG VITE_ROUTER_RPC
ARG VITE_ROUTER_GRAPH


ENV BASE_URL $BASE_URL
ENV VITE_BASE_URL $VITE_BASE_URL
ENV VITE_NETWORK $VITE_NETWORK
ENV VITE_CONTRACT_DAO $VITE_CONTRACT_DAO
ENV VITE_CONTRACT_USDT $VITE_CONTRACT_USDT
ENV VITE_ROUTER_WALLET $VITE_ROUTER_WALLET
ENV VITE_ROUTER_EXPLORER_NEAR_HASH $VITE_ROUTER_EXPLORER_NEAR_HASH
ENV VITE_URL_APIP_PRICE $VITE_URL_APIP_PRICE
ENV VITE_ROUTER_RPC $VITE_ROUTER_RPC
ENV VITE_ROUTER_GRAPH $VITE_ROUTER_GRAPH

RUN npm run build

# Stage 2: Serve Vue app with Nginx
FROM nginx:1.25.1 as prod-stage
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
